### ISSUE TITLE
November 2022 Meeting Topics

### ISSUE THREAD

**Issue by nickfarrow** [MelbourneBitDevs/MelbBitDevs#2]

**Comment by nickfarrow** [comment]
FTX explosion, zero bitcoin on balance sheet, and following contagion

**Comment by nickfarrow** [comment]
Binance clogs the mempool
https://twitter.com/ziggamon/status/1592613046421426179

**Comment by nickfarrow** [comment]
Optech RBF discussion
https://bitcoinops.org/en/newsletters/2022/10/26/

**Comment by nickfarrow** [comment]
(self plug)
Nolooking umbrel app for opening multiple lightning channels at once
https://nolooking.chaincase.app/

**Comment by pfal99** [comment]
Burak strikes again
https://twitter.com/brqgoo/status/1587397646125260802

**Comment by nickfarrow** [comment]
Nice one @adamharry , idk how i missed that (LND updating PTSD maybe)

Lightning tournament finalists:
https://twitter.com/boltfun_btc/status/1597303111319982080
(would be cool to go through a few of these, maybe i'll do a nolooking demo?)

**Comment by nickfarrow** [comment]
"Bit-thereum revisited: Announcement free DLCs"
https://mailmanlists.org/pipermail/dlc-dev/2022-August/000150.html
https://bitcoinops.org/en/newsletters/2022/08/17/
