### ISSUE TITLE
March 2023 Meeting Topics

### ISSUE THREAD

**Issue by nickfarrow** [MelbourneBitDevs/MelbBitDevs#4]
Link anything you'd like to discuss: news, demos, drama, whatever!

**Comment by BBlackwo** [comment]
Would be cool to learn more about [Breeze SDK](https://medium.com/breez-technology/lightning-for-everyone-in-any-app-lightning-as-a-service-via-the-breez-sdk-41d899057a1d) and maybe create a demo app

**Comment by nickfarrow** [comment]
Confidential transactions tutorial
https://elementsproject.org/elements-code-tutorial/confidential-transactions
(if we did this one id probably want to understand the cryptography a bit better in order to get more out of it):

**Comment by archenfuse** [comment]
If we want to get hands on we could revisit Base58 tour of Core LN on replit

**Comment by nickfarrow** [comment]
LinkingLion (chainanalysis):
https://b10c.me/observations/06-linkinglion/

Musig BIP:
https://twitter.com/real_or_random/status/1640337134199640065

Route blinding:
https://twitter.com/realtbast/status/1640606307924291585

UTreeXO Floresta Electrum Server:
https://twitter.com/Erik17192799/status/1640831466085990400?s=20

Another core maintainer steps down:
https://bitcoinmagazine.com/technical/bitcoin-core-maintainer-marco-falke-to-step-down

Codex32:
https://github.com/bitcoin/bips/pull/1425

Tari restraining order over Lightning labs:
https://www.theblock.co/post/219992/blockchain-startup-tari-labs-wins-restraining-order-against-lightning-labs-over-taro-protocol

Rollups on Bitcoin:
https://twitter.com/RollkitDev/status/1632438374513676288?s=20
