### ISSUE TITLE
April 2023 Meeting Topics

### ISSUE THREAD

**Issue by nickfarrow** [MelbourneBitDevs/MelbBitDevs#5]
Link anything you'd like to discuss: news, demos, drama, whatever!

**Comment by nickfarrow** [comment]
https://mullvad.net/en/blog/2023/4/20/mullvad-vpn-was-subject-to-a-search-warrant-customer-data-not-compromised/

**Comment by nickfarrow** [comment]
Reminder that https://learning.chaincode.com/#seminars exists and are free!

**Comment by nickfarrow** [comment]
RBG update:
https://bitcoinops.org/en/newsletters/2023/04/19/

Proposal to remove BIP35 mempool messages
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-April/021562.html
https://bitcoinops.org/en/newsletters/2023/04/26/

New StratumV2 reference implementation
https://stratumprotocol.org/blog/stratumv2-jn-announcement/

**Comment by nickfarrow** [comment]
Civkit paper
https://github.com/civkit/paper/blob/main/civ_kit_paper.pdf

MonstroP2P
https://github.com/MostroP2P/mostro

Don't download witnesses for assumed-valid blocks when running in prune mode
https://github.com/bitcoin/bitcoin/pull/27050

**Comment by BBlackwo** [comment]
Fedipool https://twitter.com/ODELL/status/1647945114424147969

**Comment by nickfarrow** [comment]
Nunchuck response
https://www.theblaze.com/news/bitcoin-wallet-exposes-ineptitude-of-canadian-govt-with-blistering-response-after-court-tries-to-freeze-crypto-assets

Inscription numbers broken
https://twitter.com/veryordinally/status/1646079834559328256

BTCMap (spend bitcoin locally)
https://btcmap.org/map#12/-37.80246/144.93027


Pheonix wallet node on amboss.space
https://amboss.space/node/03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f

**Comment by BBlackwo** [comment]
Podcast about Pegasus spyware https://www.whatbitcoindid.com/podcast/the-corruption-of-power-influence
