### ISSUE TITLE
June 2023 Meeting Topics

### ISSUE THREAD

**Issue by dragon-foobar** [MelbourneBitDevs/MelbBitDevs#7]
Link anything you'd like to discuss: news, demos, drama, whatever!

**Comment by ttiiggss** [comment]
### Would love to have a group discussion regarding RGB -  The more the merrier in this topic I think! ### 

Here is the blackpaper (it's a long paragraph so nothing too big but highlights the benefits of RGB)
https://github.com/RGB-WG/blackpaper

**Comment by thomasWos** [comment]
Interesting usage of Bitcoin security for many chains. Basically add a timestamp to Bitcoin as a checkpoint.
https://www.babylonchain.io/
https://www.youtube.com/watch?v=Dl2EU4UHbU0

<img width="939" alt="Screenshot 2023-05-29 at 7 15 23 pm" src="https://github.com/MelbourneBitDevs/MelbBitDevs/assets/785740/f0121c03-10f8-4826-a01f-9f0edaf2379b">
https://babylonscan.io/  - Currently in testnet

**Comment by BBlackwo** [comment]
[A Beginner-Friendly Guide to Modifying Open Source Projects](https://bitcoiner.guide/fork/)

**Comment by nickfarrow** [comment]
Adding and Removing Multisig Signers with FROST
(Let's just cover overview of what's possible)
https://gist.github.com/nickfarrow/64c2e65191cde6a1a47bbd4572bf8cf8/

**Comment by nickfarrow** [comment]
Tor introduces proof-of-work
https://gitlab.torproject.org/tpo/core/torspec/-/blob/main/proposals/327-pow-over-intro.txt
https://darknetone.com/tor-merges-proof-of-work-to-combat-ddos-attacks/

**Comment by nickfarrow** [comment]
The curious case of the half-half Bitcoin ECDSA nonces
> an apparently custom ECDSA/Bitcoin implementation that has been used to empty hundreds of compromised Bitcoin addresses for many years.

https://eprint.iacr.org/2023/841

**Comment by BBlackwo** [comment]
https://lightningdevkit.org/blog/announcing-ldk-node/

[No BS Bitcoin Summary](https://www.nobsbitcoin.com/introducing-ldk-node/)
