### ISSUE TITLE
August 2023 Meeting Topics

### ISSUE THREAD

**Issue by nickfarrow** [MelbourneBitDevs/MelbBitDevs#9]
Link anything you'd like to discuss: news, demos, drama, whatever!

**Comment by nickfarrow** [comment]
Milk Sad

Command line tool `bx` from libbitcoin (recommended in Mastering Bitcoin) has a severe lack of entropy for creating seeds. Some wallets are said to be using this tool. Likely millions of dollars stolen.

https://milksad.info/

**Comment by M3rkl3-Tr33** [comment]
The Guys behind cDc Just did a presentation @ DEFCON31
https://gitlab.com/veilid
https://veilid.com/Launch-Slides-Veilid.pdf
Looks to be a New TOR Framework might be early days yet.

**Comment by ttiiggss** [comment]
A unique bitcoin-denominated investment vehicle designed to capitalize on anticipated ASIC market rebounds ahead of the next Bitcoin halving in 2024.

[https://habla.news/u/Blockstream@blockstream.com/1692157352910](url)

**Comment by ttiiggss** [comment]
The First Native Nostr Assets Protocol (uses bitcoin taproot)

[](https://doc.nostrassets.com/)

[](https://www.youtube.com/watch?v=tXrY8gnSmsA)

**Comment by BBlackwo** [comment]
Tornado Cash Developers Charged with Money Laundering and Sanctions Violations by US Govt

https://www.nobsbitcoin.com/tornado-cash-developers-charged-with-money-laundering-and-sanctions-violations/

**Comment by BBlackwo** [comment]
Tor launched proof of work defence for onion services

https://www.nobsbitcoin.com/tor-launched-proof-of-work-defense-for-onion-services/

**Comment by BBlackwo** [comment]
Miniscript (from Trick):

I’m gonna forget if I don’t say this now but if we have time can we touch on miniscript? They’re trying to enable more complex utxo ownership incl timestamp or blockheight ( I think)

https://fountain.fm/episode/JfTKfsIQUhBHSf1Hmcd2

**Comment by smolgrrr** [comment]
Drivechains 😅

**Comment by nickfarrow** [comment]
Private Collaborative Custody with FROST
(if you don't cover this month, ill be there to explain next month)

https://twitter.com/utxoclub/status/1696458566658376119

**Comment by matias-seer** [comment]
Green light
https://blockstream.com/lightning/greenlight/

**Comment by BBlackwo** [comment]
Other topics discussed:
 - [BTC Sessions - Using dice to create a wallet](https://www.youtube.com/watch?v=LxTkLwpV1Po)
 - Discreet Log Contracts
 - Mutiny building "Synthetic dollars via DLCs" - https://blog.mutinywallet.com/introducing-mutiny/
 - Bitaxe - https://github.com/skot/bitaxe
